config/routes.rb
Rails.application.routes.draw do
  namespace :api, path: '/', constraints: { subdomain: 'api' } do
    resources :mods, only: [:index, :show]
    resources :categories, only: [:index, :show] do
      resources :mods, only: :index
    end
    resources :authors, only: [:index, :show] do
      resources :mods, only: :index
    end
    resources :users, only: [] do
      resources :bookmarks, only: :index
    end
    root to: 'api#root'
  end

  devise_for :users,
              path: 'account',
              path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' },
              controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  # It's open source so really no much obscurity,
  # but at least it will deter a few automated crawlers
  scope 'potato' do
    ActiveAdmin.routes(self)
    get '/', to: 'admin/dashboard#index'
  end

  resources :authors, only: [:show]
  resources :bookmarks, only: [:create, :index] do
    delete :destroy, on: :collection
  end

  # Routes examples
  #
  # /mods
  # /mods/new
  # /mods/:id
  # /mods/:id/edit
  #
  # /recently-updated-mods
  # /recently-updated-mods/category/:id
  # /most-downloaded-mods
  # /most-downloaded-mods/category/:id
  #
  # /category/:id

  scope '/', as: :alpha, sort: 'alpha' do
    resources :mods, only: :index
    resources :categories, path: 'category', only: [] do
      resources :mods, path: '/', only: :index
    end
  end

  scope '/recently-updated', sort: 'most_recent', as: :most_recent do
    resources :mods, path: '/', only: :index
    resources :categories, path: 'category', only: [] do
      resources :mods, path: '/', only: :index
    end
  end

  # scope '/most-downloaded', sort: 'most_downloaded', as: :downloads do
  #   resources :mods, path: '/', only: :index
  #   resources :categories, path: 'category', only: [] do
  #     resources :mods, path: '/', only: :index
  #   end
  # end

  scope '/most-popular', sort: 'popular', as: :popular do
    resources :mods, path: '/', only: :index
    resources :categories, path: 'category', only: [] do
      resources :mods, path: '/', only: :index
    end
  end

  # scope '/most-forum-comments', sort: 'popular', as: :forum_comments do
  #   resources :mods, path: '/', only: :index
  #   resources :categories, path: 'category', only: [] do
  #     resources :mods, path: '/', only: :index
  #   end
  # end

  resources :mods

  # This one is for the helper
  resources :categories, path: 'category', only: [] do
    resources :mods, path: '/', only: :index
  end

  resources :forum_validations, path: 'forum-validations', only: [:new, :show, :create] do
    member do
      get '/validate', to: 'forum_validations#update', as: :update
    end
  end

  get '/how-to-submit' => 'static#how_to_submit', as: :how_to_submit_static
  get '/how-to-install' => 'static#how_to_install', as: :how_to_install_static
  get '/how-to-make' => 'static#how_to_make', as: :how_to_make_static

  root to: 'mods#index', sort: 'most_recent'
end

app/views/layouts/_footer.html.haml
.footer
  :markdown
    FactorioMods &copy; #{Time.now.year}
    - Not an official [Factorio](http://www.factorio.com/) app
    - [Source code on Github](http://github.com/Zequez/FactorioMods)
    - [Factorio subreddit](http://reddit.com/r/factorio 'Reddit community is best community')
    - [Factorio forums](http://www.factorioforums.com/forum/)

app/views/layouts/_google_analytics.html.haml
- if Rails.env.production?
  :javascript
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', '#{Rails.configuration.ga_ua}', '#{Rails.configuration.ga_url}');
    document.addEventListener('page:change', function(ev){
      ga('send', 'pageview');
    });

app/views/layouts/_header.html.haml
.header
  %h1.logo
    %a{href: '/'}
      Fact<i class="fa fa-cog"></i><span>o</span>ri<i class="fa fa-cog"></i><span>o</span>
      M<i class="fa fa-cog"></i><span>o</span>ds
  .user-session
    - if user_signed_in?
      = link_to current_user.name, edit_user_registration_path
      |
      = link_to t('.sign_out'), destroy_user_session_path
    - else
      = link_to t('.sign_in'), new_user_session_path
      |
      = link_to t('.sign_up'), new_user_registration_path
  .instructions
    .instructions-buttons
      = t('.how_to.start')
      %a{href: how_to_install_static_url}= t('.how_to.install')
      \/
      %a{href: how_to_make_static_url}= t('.how_to.make')
      \/
      %a{href: how_to_submit_static_url}= t('.how_to.submit')
      = t('.how_to.end')
      %a{href: new_mod_path}= t('.submit_mod')

app/views/layouts/_search_bar.html.haml
.search-bar
  %ul.sorters
    %li.sorter><
      = sort_link :most_recent do
        = icon 'history', t('.most_recent')
    %li.sorter><
      = sort_link :alpha do
        = icon 'sort-alpha-asc', t('.alpha')
    %li.sorter<>
      = sort_link :popular do
        = icon 'star-o', t('.popular')
    %li.sorter<>
      = sort_link bookmarks_path do
        = icon 'star', t('.bookmarked')
  .text-filter
    = search_form do
      %input.input.input-text.input-text-search#search-input{type: 'text', placeholder: t('.search'), name: 'q', value: params[:q], maxlength: 30}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title= yield :title
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Titillium+Web:400,600'
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags
    %link(rel="shortcut icon" href="/favicon.ico?v=2")
    = render partial: 'layouts/google_analytics'
  %body{class: body_controller_classes}
    #official-app-banner
      Hey! The official Factorio mods app is up and running!<br/>
      Stop using this one and go to <a href="http://mods.factorio.com">http://mods.factorio.com</a><br/>
      This app will be decomissioned soon! Thanks for your support!<br/>
      <button class='btn'>I understand, hide this message</button>
    .page-wrap
      .container
        = render partial: 'layouts/header'
        = render partial: 'layouts/search_bar'
        - flash.each do |key, value|
          - unless value.blank?
            .flash{class: key}
              .flash-value= value

        .content{class: "content-#{content_layout}"}
          = yield
      .footer-spacer

    = render partial: 'layouts/footer'
    = javascript_include_tag 'application', 'data-turbolinks-eval' => false

app/views/layouts/blank_page.html.haml
.content-block
  = yield